### ISSUE TITLE
2019.10.04までのコードレビュー

### ISSUE THREAD

**Issue by cochumo** [cochumo/petgram#1]
petgram/app/Http/Controllers/PhotosController.php
　question:
　　・メソッド名に違和感がないか
　　・データがうまく取れなかった時の事の処理はどこに書いたら良いか
　　・画像のパスのつなげ方に違和感ないか
　　・インスタンス変数の定義に違和感がないか
　　・メソッド毎のコメントはどのようにしたらよいか
petgram/routes/web.php
　question:
　　・ざっと気になる点がないか確認して頂きたいです
petgram/database/migrations/2019_09_29_120220_create_photos_table.php
　question:
　　・ざっと気になる点がないか確認して頂きたいです

authの追加をしたばかりなので、そのあたりは修正していくので今回はPhotosController.phpを中心に確認お願い致します。

**Comment by nakanakamu0828** [comment]
## 1. 詳細画面のfunction名について
LaravelのCRUDの基本メソッドが

- index
- show
- create
- store
- edit
- update
- destroy

なので、`showPostDetail`は`show`という名称に変更し、他の詳細画面の処理でも`show`で統一すると把握しやすいコードになると思います。
同様に

`delete` -> `destroy`
`showCreateForm` -> `create`
`create` -> `store`

に変更するといいですね。
（deleteは悩むところですが・・・Controllerによって名称がばらけないように統一は必要だと思います）

https://github.com/cochumo/petgram/blob/f88cccd4132df9cff901492e4b5ac0f123216e47/app/Http/Controllers/PhotosController.php#L36

https://github.com/cochumo/petgram/blob/f88cccd4132df9cff901492e4b5ac0f123216e47/app/Http/Controllers/PhotosController.php#L50

## 2. Route Model Bindingの利用
Laravel wayなシンプルアプリを作り場合は、Route Model Bindingの機能を利用することで処理もシンプルにできると考えています。

例えば
https://github.com/cochumo/petgram/blob/f88cccd4132df9cff901492e4b5ac0f123216e47/app/Http/Controllers/PhotosController.php#L50-L52

このdeleteメソッド部分は

```
public function delete(Photo $photo)
{
}
```

に変更可能です。
showやedit, updateにも利用できます。ご検討ください。

注意点になりますが、ルーティングでは
https://github.com/cochumo/petgram/blob/f88cccd4132df9cff901492e4b5ac0f123216e47/routes/web.php#L24
↓
`{id}` を `{photo}`のようにモデル名に変更する必要があります。

https://laravel.com/docs/5.8/routing#route-model-binding

## 3. パスの定義について
https://github.com/cochumo/petgram/blob/f88cccd4132df9cff901492e4b5ac0f123216e47/app/Http/Controllers/PhotosController.php#L12-L15

↑
この部分は定数定義でいいと思います。constを利用して定義してみてください。
あと、外部から利用しない変数はprivateにした方がいいですね。

このパスはPhotoモデルに定義して、Modelの変数やfunctionとして画像URLを取得できるようにするとさらに良いかなと思います。
私は、
```
public function getUrlAttribute(): string
{
        return asset('storage/' . static::FILE_DIR . '/' . $this->file);
}
```
このようにModelのattributeとして画像URLを定義し、`$model->url` で取得できるようにしています。今回は、image_urlとかの方がattribute名としては適していそうですね。

## 4. docについて
私もそこまで詳しくdocを各プロジェクトはないのですが、phpdocのフォーマットを参考にしてdocを書くようにしています。
基本的にはソースを見れば仕様がわかるというのが大前提だと思います。
コメントなどは極力なしで、仕様的にどうしても複雑になる場合のみコメントするようにしています。

https://www.phpdoc.org/

## 5. 配列について
https://github.com/cochumo/petgram/blob/f88cccd4132df9cff901492e4b5ac0f123216e47/app/Http/Controllers/PhotosController.php#L94-L98
↑
配列の定義として、`[]`が利用できるようになってからarray関数は使うことが少なくなってきました。私は`[]`で統一するようにしています。
コード量が少ない方が見やすいソースになり易いのでご検討ください。

## 5. マイグレーションファイルについて
特に問題ありません。セミコロンが重複してたので気になりました！

https://github.com/cochumo/petgram/blob/f88cccd4132df9cff901492e4b5ac0f123216e47/database/migrations/2019_09_29_120220_create_photos_table.php#L18
