### ISSUE TITLE
現状の問題点、2019.10.29までのコードレビュー

### ISSUE THREAD

**Issue by cochumo** [cochumo/petgram#2]
## 投稿確認ページでの離脱について
現在、投稿確認ページで投稿をせず離脱した場合`petgram/storage/app/public/temp`にtempファイルが残ってしまうので困っています。
`petgram/public/js/common.js`にて

1. 投稿確認ページから離脱を感知する
2. 離脱確認ポップアップを表示
3. 「離脱する」を押すとformを使ってtempファイルの削除処理を行う

という処理も実装したのですが、「戻る」「進む」「ページを閉じる」などの操作をした際などまで見切れません。
そもそも確認の時点でtempにファイルを置くこと自体が問題なのかとも思うのですがご意見いただけますでしょうか。

## login,logoutの際に419が返される
2重submitの影響か419エラーが返されてしまうのですが、loginのみJSにて対応したのですが、loginも頻度は減ったものの、セッションが切れたタイミング(?)などでlogout,loginをしていると419が返されることがあります。(正確には発生条件を出せていません)
サーバー側でどのように対応していけばよいでしょうか？

## 投稿のコメントの代わりにリアクションを実装したい
こちらのアプリでは「ネガティブ」を排除したいと考えておりコメント欄にて誹謗中傷を防ぐために今後、コメントの代わりとしてslackのリアクションのような機能を実装したいと考えているのですがどのように実装していけばよいか想定していただけないでしょうか。
いいね！機能あたりを参考にDBを設計し、Counter Cacheなどを使ってカウントして実装できないだろうかと考えております。

### petgram/public/js/common.js
気になる点

- 共同開発者がJQueryの3系はon('load')が動作しないので下に別で記載しているのですがloadなどがonに統一されただけで普通に使えるのですがどちらがスマートでしょうか？
https://wemo.tech/109

- 全体的に気になる点あげていただきたいです！

### petgram/app/Http/Controllers/PhotosController.php
VPSなので画像の容量を下げたいと考え、store functionの中にExif情報の削除とリサイズ処理を追加したので気になる点あげていただきたいです！

**Comment by yuki-nakamura** [comment]
## 投稿確認ページでの離脱について
```
現在、投稿確認ページで投稿をせず離脱した場合petgram/storage/app/public/tempにtempファイルが残ってしまうので困っています。
```
投稿完了した場合は、tempディレクトリから他のディレクトリに移動されますよね？
なので、tempディレクトリに残りっぱなしの画像は利用しない画像と判断していいと思います。バックエンド（サーバー側）でバッチで一定期間経過したファイルを削除するバッチを作るのがいいのでは？っと思います。

## login,logoutの際に419が返される
CSRFトークンの有効期間が切れたことが原因だと思います。
logout処理については、HTTPリクエストのメソッドをGetに切り替えてもいいかもしれませんが、頻発するのはちょっとおかしいですね。。。
ソース落としてきて動かしてみます。

## 投稿のコメントの代わりにリアクションを実装したい
他の案件でメッセージにリアクションをつけたいという機能があって。

https://atomiks.github.io/tippyjs/

UIはtippy.jsを導入しました。Slackのように追加、削除、カウントアップ/ダウンとなると小テーブルでリアクション情報持った方が良さそうですね。リアクションが固定されていれば、単純にカウントアップ/ダウンだけでできそうですね。

**Comment by nakanakamu0828** [comment]
## 投稿確認ページでの離脱について
```
現在、投稿確認ページで投稿をせず離脱した場合petgram/storage/app/public/tempにtempファイルが残ってしまうので困っています。
```
投稿完了した場合は、tempディレクトリから他のディレクトリに移動されますよね？
なので、tempディレクトリに残りっぱなしの画像は利用しない画像と判断していいと思います。バックエンド（サーバー側）でバッチで一定期間経過したファイルを削除するバッチを作るのがいいのでは？っと思います。

## login,logoutの際に419が返される
CSRFトークンの有効期間が切れたことが原因だと思います。
logout処理については、HTTPリクエストのメソッドをGetに切り替えてもいいかもしれませんが、頻発するのはちょっとおかしいですね。。。
ソース落としてきて動かしてみます。

## 投稿のコメントの代わりにリアクションを実装したい
他の案件でメッセージにリアクションをつけたいという機能があって。

https://atomiks.github.io/tippyjs/

UIはtippy.jsを導入しました。Slackのように追加、削除、カウントアップ/ダウンとなると小テーブルでリアクション情報持った方が良さそうですね。リアクションが固定されていれば、単純にカウントアップ/ダウンだけでできそうですね。

**Comment by nakanakamu0828** [comment]
## petgram/public/js/common.js

> 共同開発者がJQueryの3系はon('load')が動作しないので下に別で記載しているのですがloadなどがonに統一されただけで普通に使えるのですがどちらがスマートでしょうか？
> https://wemo.tech/109

https://www.wakuwakubank.com/posts/614-javascript-async-defer/

scriptタグにdeferをつけている場合、HTMLのパースを待ってからjsが実行されるので、jQueryでロードをまたなくても実装できるようになりました。
common.jsにdeferが付いていたら特にload意識せずに実装していいと思います。

あと、common.jsですが、constなどES6移行の実装がありますが、古めのブラウザだと動かないと思うので注意してください。

**Comment by cochumo** [comment]
## 投稿確認ページでの離脱について

> バックエンド（サーバー側）でバッチで一定期間経過したファイルを削除するバッチを作るのがいいのでは？っと思います。
https://w1563790639-qxm297179.slack.com/archives/CP3K5PSAH/p1572244201000400
https://qiita.com/katsukii/items/f62236b2a6de5d473eaa
こちらの2件を使った実装と考えでよかったでしょうか？

**Comment by nakanakamu0828** [comment]
tmpwatchコマンドってはじめて知りました 笑

いつも私はfindコマンドを利用してやってました。
http://www.rep1.co.jp/staff/200vcxg/217rav/find_n_lcd_-linux_command_dict.htm
https://qiita.com/narumi_/items/9ea27362a1eb502e2dbc


tmpwatchコマンドでできればそれでも問題ないです！
