### ISSUE TITLE
サムネイル画像の編集時の戻るボタン実装について

### ISSUE THREAD

**Issue by cochumo** [cochumo/petgram#4]
## 前提
・現在、サムネイルの変更処理を書いていて変更自体はほぼ完成しているのですが戻るボタンの実装で詰まっています。
サムネイル変更の流れとしましては...

1. サムネイルとなる画像のアップロード
2. アップロードされた画像のトリミング位置の調整
3. トリミングされた画像の確認
4. 完了（TOPへ戻る）

と、なります。
・現在、画像ファイルの持ち方がひとつのファイルを加工して、それを保存するというトリミングの位置を再調整するということを想定していない処理になっているのでこちらは後々修正します。
## 本題
上記の3から2にも戻る処理で詰まっています。
3で下記のようにactionのvalueでユーザーが修正したいのか、そうではないのかを判断できるようにし
https://github.com/cochumo/petgram/blob/c5a773d49dc9170149ac00bd18da60c81299762f/resources/views/users/thumbnail/confirm.blade.php#L12-L13

下記のように記述しましたが、トップ(/photos)に飛ばされてしまい2に飛んでくれませんでした。
https://github.com/cochumo/petgram/blob/c5a773d49dc9170149ac00bd18da60c81299762f/app/Http/Controllers/ThumbnailController.php#L139

このような場合どうしたらよいでしょうか？またどこがうまくいっていなくてトップ(/photos)に飛ばされてしまうのか調べる方法を教えて頂きたいです。

**Comment by nakanakamu0828** [comment]
@cochumo 
多分ですが・・・
cropという画面はpostで受け付ける処理になっているかと思います。
なので、redirectで画面を戻ろうとしてもgetでのアクセスになるのでcorp画面が表示できないんじゃないでしょうか？

現状のcrop処理だと画像がアップロードされる前提なので、バックで戻るというのを許容できない設計になってそうですね。
今すぐ思いつく方法としては、cropをgetも許容し、getアクセスの場合はファイルがアップロードされないので、バリデーションはスキップ。getに沿った処理を追加

という感じになりそうです。
